### ISSUE TITLE
Make it more clear from the name that this is not an official extension

### ISSUE THREAD

**Issue by colszowka** [kddeisz/rubytoolbox-chrome#1]
Hey @kddeisz, first of all very nice idea, I think this will be useful, well done!

I would appreciate if the extension could get a less generic name on the Chrome Web Store. Due to the use of the toolbox logo and name for the extension as it stands the only possibility to figure out this is not an "official" extension is to know that you, the publisher are not directly associated with the Toolbox. I would suggest to name it something like "Ruby Toolbox data on Rubygems.org". 

This suggestion is absolutely not intended cast any doubt about your trustworthiness or anything, I just think it should be clear and transparent to users what's the source of something they install on their machine so I think in that regard it would be helpful to have a clearer understanding on that as having something using the Toolbox logo and name without further explanation would surely lead potential users to believe this is an official plugin directly by the Ruby Toolbox.

Thanks you!

**Comment by kddeisz** [comment]
Hey @colszowka, 

Yeah I can totally understand that - I was thinking about this when I was first making it and I was wondering if I should have contacted you - apologies for not doing that. I can absolutely take it down rename and reupload.

Would you be interested at all in making it an official thing? Having it live under the rubytoolbox user? I'd be happy to maintain it. Just an offer, no pressure either way.

**Comment by kddeisz** [comment]
Hey @colszowka sorry it took me absolutely forever to do this but I've reuploaded it as Ruby Toolbox data on Rubygems.org and hopefully it'll get approved.
